version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "thumbnailer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sjv2xu110o4m"
s3_prefix = "thumbnailer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
